## Vagrantfile for haskell-box
## Mac Radigan, Eric Paniagua

  Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/yakkety64"

    config.vm.provider "virtualbox" do |v|
      v.name = "Common Lisp Development Environment"
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end

    config.ssh.insert_key    = true
    config.ssh.forward_x11   = true
    config.ssh.forward_agent = true
    config.ssh.shell         = "/bin/bash"

    config.vm.provision :shell, :path => "bootstrap.sh"
  end

## *EOF*
