## Vagrantfile for av-dev
## Mac Radigan, Eric Paniagua

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.name = "Go Development Environment"
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.ssh.insert_key = false

  config.vm.provision :shell, :path => "bootstrap.sh"
end

## *EOF*
