## BUILD

  package(
    default_visibility = ["//visibility:public"],
  )

  load("//go:def.bzl", "go_library", "go_test")

  go_library(
    name = "go_default_library",
    srcs = [
      "lib.go",
    ],
  )

## *EOF*
